# Deployment do MongoDB

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb  
spec:
  selector:
    matchLabels:
      app: mongodb      
  template:
    metadata:
      labels:
        app: mongodb        
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0.5
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd

---
# Service do MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
  type: ClusterIP

---

# Deploymento da Aplicação Rotten Potatoes

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rottenpotatoes
spec:
  selector:
    matchLabels:
      app: rottenpotatoes
  template:
    metadata:
      labels:
        app: rottenpotatoes
    spec:
      containers:
      - name: rottenpotatoes
        image: zanryuga/rotten-potatoes:v1
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: admin
        - name: MONGODB_HOST
          value: mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: mongouser
        - name: MONGODB_PASSWORD
          value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: rottenpotatoes
spec:
  selector:
    app: rottenpotatoes
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer
